### ISSUE TITLE
Sass::SyntaxError

### ISSUE THREAD

**Issue by weshysell** [twbs/bootstrap-sass#1026]
On a fairly fresh rails application I'm receiving the following error:

> Invalid CSS after "... $border-radius": expected "{", was ";"

**app/assets/stylesheets/application.scss**
```
@import "bootstrap-sprockets";
@import "bootstrap";
```

**bundle list**
```
Gems included by the bundle:
  * actionmailer (4.2.5.1)
  * actionpack (4.2.5.1)
  * actionview (4.2.5.1)
  * activejob (4.2.5.1)
  * activemodel (4.2.5.1)
  * activerecord (4.2.5.1)
  * activesupport (4.2.5.1)
  * arel (6.0.3)
  * autoprefixer-rails (6.3.3.1)
  * bcrypt (3.1.10)
  * binding_of_caller (0.7.2)
  * bootstrap-sass (3.3.6)
  * builder (3.2.2)
  * bundler (1.7.6)
  * byebug (8.2.2)
  * cancancan (1.13.1)
  * coffee-rails (4.1.1)
  * coffee-script (2.4.1)
  * coffee-script-source (1.10.0)
  * concurrent-ruby (1.0.1)
  * debug_inspector (0.0.2)
  * diff-lcs (1.2.5)
  * domain_name (0.5.20160309)
  * erubis (2.7.0)
  * execjs (2.6.0)
  * factory_girl (4.5.0)
  * factory_girl_rails (4.6.0)
  * globalid (0.3.6)
  * http-cookie (1.0.2)
  * i18n (0.7.0)
  * ice_cube (0.14.0)
  * jbuilder (2.4.1)
  * jquery-rails (4.1.0)
  * json (1.8.3)
  * loofah (2.0.3)
  * mail (2.6.3)
  * mime-types (2.99.1)
  * mini_portile2 (2.0.0)
  * minitest (5.8.4)
  * multi_json (1.11.2)
  * mysql2 (0.4.3)
  * netrc (0.11.0)
  * nokogiri (1.6.7.2)
  * rack (1.6.4)
  * rack-test (0.6.3)
  * rails (4.2.5.1)
  * rails-deprecated_sanitizer (1.0.3)
  * rails-dom-testing (1.0.7)
  * rails-html-sanitizer (1.0.3)
  * rails_real_favicon (0.0.3)
  * railties (4.2.5.1)
  * rake (10.5.0)
  * rdoc (4.2.2)
  * rest-client (1.8.0)
  * rspec-core (3.4.3)
  * rspec-expectations (3.4.0)
  * rspec-mocks (3.4.1)
  * rspec-rails (3.4.2)
  * rspec-support (3.4.1)
  * rubyzip (1.2.0)
  * sass (3.4.21)
  * sass-rails (5.0.4)
  * sdoc (0.4.1)
  * spring (1.6.4)
  * sprockets (3.5.2)
  * sprockets-rails (3.0.3)
  * sqlite3 (1.3.11)
  * thor (0.19.1)
  * thread_safe (0.3.5)
  * tilt (2.0.2)
  * turbolinks (2.5.3)
  * tzinfo (1.2.2)
  * uglifier (2.7.2)
  * unf (0.1.4)
  * unf_ext (0.0.7.2)
  * web-console (2.3.0)
```

**Last Several Lines of the Framework Trace**
```
bootstrap-sass (3.3.6) assets/stylesheets/bootstrap/mixins/_buttons.scss:64
bootstrap-sass (3.3.6) assets/stylesheets/bootstrap/_mixins.scss:21
bootstrap-sass (3.3.6) assets/stylesheets/_bootstrap.scss:9
sass (3.4.21) lib/sass/scss/parser.rb:1179:in `expected'
sass (3.4.21) lib/sass/scss/parser.rb:1115:in `expected'
sass (3.4.21) lib/sass/scss/parser.rb:1110:in `tok!'
sass (3.4.21) lib/sass/scss/parser.rb:654:in `block'
sass (3.4.21) lib/sass/scss/parser.rb:724:in `declaration_or_ruleset'
sass (3.4.21) lib/sass/scss/parser.rb:674:in `block_child'
sass (3.4.21) lib/sass/scss/parser.rb:666:in `block_contents'
sass (3.4.21) lib/sass/scss/parser.rb:655:in `block'
sass (3.4.21) lib/sass/scss/parser.rb:232:in `mixin_directive'
sass (3.4.21) lib/sass/scss/parser.rb:220:in `special_directive'
sass (3.4.21) lib/sass/scss/parser.rb:195:in `directive'
sass (3.4.21) lib/sass/scss/parser.rb:673:in `block_child'
sass (3.4.21) lib/sass/scss/parser.rb:666:in `block_contents'
sass (3.4.21) lib/sass/scss/parser.rb:123:in `stylesheet'
sass (3.4.21) lib/sass/scss/parser.rb:39:in `parse'
sass (3.4.21) lib/sass/engine.rb:403:in `_to_tree'
sass (3.4.21) lib/sass/engine.rb:309:in `to_tree'
```

**Comment by thomas-mcdonald** [comment]
Seems strange given that line looks [very valid](https://github.com/twbs/bootstrap-sass/blame/v3.3.6/assets/stylesheets/bootstrap/mixins/_buttons.scss#L64), and hasn't changed since 2014.

Are you setting `$border-radius` to something different?

**Comment by cvrebert** [comment]
Closing due to lack of response to @thomas-mcdonald's question.
