### ISSUE TITLE
Font URLs referred in the CSS are invalid in the dev env

### ISSUE THREAD

**Issue by mspanc** [twbs/bootstrap-sass#590]
I use RoR 4.1 along with bootstrap-sass 3.1.1.1.

In the development environment I get errors in the console about missing fonts:

```
ActionController::RoutingError (No route matches [GET] "/fonts/glyphicons-halflings-regular.svg"):
  actionpack (4.1.0) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.1.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.0) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.0) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.0) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.0.2) lib/quiet_assets.rb:18:in `call_with_quiet_assets'
  actionpack (4.1.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.0) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.0) lib/action_dispatch/middleware/static.rb:64:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.0) lib/rails/engine.rb:514:in `call'
  railties (4.1.0) lib/rails/application.rb:144:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  rack (1.5.2) lib/rack/content_length.rb:14:in `call'
  rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'
  /home/marcin/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
  /home/marcin/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
  /home/marcin/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

I've found out that if I use the following URL: `assets/bootstrap/glyphicons-halflings-regular.woff` everything works properly. Seems that the "bootstrap" prefix is missing in the dev env (I guess it is stripped in production during assets compilation phase?)

**Comment by genghuiluo** [comment]
revert to 3.2.00 can't fix this bug

**Comment by evilsideburns** [comment]
Using `boostrap-sass` 3.3.7 under Rails 5.2.3. CSS manifest includes:

```scss
@import "bootstrap-sprockets";
@import "bootstrap";
```

Glyphicons DO appear, but I am still getting these regularly in my log file:

```
ActionController::RoutingError (No route matches [GET] "/fonts/bootstrap/glyphicons-halflings-regular.svg")
```
