### ISSUE TITLE
rake convert windows

### ISSUE THREAD

**Issue by quasiperfect** [twbs/bootstrap-sass#670]
is rake convert working under windows ?

i tried and get

```
** Invoke convert (first_time)
** Execute convert
rake aborted!
SyntaxError: D:/UniServerZ/www/bootstrap-sass-master/tasks/converter.rb:37: synt
ax error, unexpected tLABEL, expecting ')'
  def initialize(repo: 'twbs/bootstrap', branch: 'm...
                      ^
D:/UniServerZ/www/bootstrap-sass-master/tasks/converter.rb:37: syntax error, une
xpected ',', expecting keyword_end
...tialize(repo: 'twbs/bootstrap', branch: 'master', save_to: {...
...                               ^
D:/UniServerZ/www/bootstrap-sass-master/tasks/converter.rb:37: syntax error, une
xpected ',', expecting keyword_end
...s/bootstrap', branch: 'master', save_to: {}, cache_path: 'tm...
...                               ^
D:/UniServerZ/www/bootstrap-sass-master/tasks/converter.rb:37: syntax error, une
xpected ')', expecting keyword_end
D:/UniServerZ/www/bootstrap-sass-master/tasks/converter.rb:80: syntax error, une
xpected keyword_end, expecting $end
D:/UniServerZ/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.
rb:54:in `require'
D:/UniServerZ/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.
rb:54:in `require'
D:/UniServerZ/www/bootstrap-sass-master/Rakefile:25:in `block in <top (required)
>'
D:/UniServerZ/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:240:
in `call'
D:/UniServerZ/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:240:
in `block in execute'
D:/UniServerZ/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:235:
in `each'
D:/UniServerZ/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:235:
in `execute'
D:/UniServerZ/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:179:
in `block in invoke_with_call_chain'
D:/UniServerZ/Ruby193/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
D:/UniServerZ/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:172:
in `invoke_with_call_chain'
D:/UniServerZ/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:165:
in `invoke'
D:/UniServerZ/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.
rb:150:in `invoke_task'
D:/UniServerZ/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.
rb:106:in `block (2 levels) in top_level'
D:/UniServerZ/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.
rb:106:in `each'
D:/UniServerZ/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.
rb:106:in `block in top_level'
D:/UniServerZ/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.
rb:115:in `run_with_threads'
D:/UniServerZ/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.
rb:100:in `top_level'
D:/UniServerZ/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.
rb:78:in `block in run'
D:/UniServerZ/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.
rb:176:in `standard_exception_handling'
D:/UniServerZ/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.
rb:75:in `run'
D:/UniServerZ/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.3.2/bin/rake:33:in `<top
(required)>'
D:/UniServerZ/Ruby193/bin/rake:23:in `load'
D:/UniServerZ/Ruby193/bin/rake:23:in `<main>'
Tasks: TOP => convert
```

**Comment by quasiperfect** [comment]
another retry

i almost got it to work

```
rake aborted!
NameError: uninitialized constant Converter::LessConversion::Bootstrap
D:/UniServerZ/www/bootstrap-sass-master/tasks/converter/less_conversion.rb:147:i
n `process_stylesheet_assets'
D:/UniServerZ/www/bootstrap-sass-master/tasks/converter.rb:63:in `process_bootst
rap'
D:/UniServerZ/www/bootstrap-sass-master/Rakefile:25:in `block in <top (required)
>'
D:/UniServerZ/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:i
n `call'
D:/UniServerZ/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:i
n `block in execute'
D:/UniServerZ/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:i
n `each'
D:/UniServerZ/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:i
n `execute'
D:/UniServerZ/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:i
n `block in invoke_with_call_chain'
D:/UniServerZ/Ruby21/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
D:/UniServerZ/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:i
n `invoke_with_call_chain'
D:/UniServerZ/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:i
n `invoke'
D:/UniServerZ/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.r
b:150:in `invoke_task'
D:/UniServerZ/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.r
b:106:in `block (2 levels) in top_level'
D:/UniServerZ/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.r
b:106:in `each'
D:/UniServerZ/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.r
b:106:in `block in top_level'
D:/UniServerZ/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.r
b:115:in `run_with_threads'
D:/UniServerZ/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.r
b:100:in `top_level'
D:/UniServerZ/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.r
b:78:in `block in run'
D:/UniServerZ/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.r
b:176:in `standard_exception_handling'
D:/UniServerZ/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.r
b:75:in `run'
D:/UniServerZ/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (
required)>'
D:/UniServerZ/Ruby21/bin/rake:23:in `load'
D:/UniServerZ/Ruby21/bin/rake:23:in `<main>'
Tasks: TOP => convert
```

any ideea ?
