### ISSUE TITLE
undefined method `[]' for nil:NilClass when using commit hash

### ISSUE THREAD

**Issue by bassjobsen** [twbs/bootstrap-sass#735]
I try to run: `rake -v convert[a365d8689c3f3cee7f1acf86b61270ecca8e106d]` which should as i understood work with https://github.com/twbs/bootstrap/commit/a365d8689c3f3cee7f1acf86b61270ecca8e106d

The output of the above:

```
Convert Bootstrap LESS to SASS
 repo   : https://github.com/twbs/bootstrap
 branch : a365d8689c3f3cee7f1acf86b61270ecca8e106d https://github.com/twbs/bootstrap/tree/a365d8689c3f3cee7f1acf86b61270ecca8e106d
 save to: {"js":"assets/javascripts/bootstrap","scss":"assets/stylesheets/bootstrap","fonts":"assets/fonts/bootstrap"}
 twbs cache: tmp/converter-cache-bootstrap
------------------------------------------------------------
Processing fonts...
  CACHED GET https://api.github.com/repos/twbs/bootstrap/git/trees/a365d8689c3f3cee7f1acf86b61270ecca8e106d...
  CACHED GET https://api.github.com/repos/twbs/bootstrap/git/trees/05ea5c382cdc7abe948d5ebe0822de2495d2ecef...
  CACHED GET 4 files from https://raw.githubusercontent.com/twbs/bootstrap/a365d8689c3f3cee7f1acf86b61270ecca8e106d/fonts glyphicons-halflings-regular.eot glyphicons-halflings-regular.svg glyphicons-halflings-regular.ttf glyphicons-halflings-regular.woff...
Processing stylesheets...
  CACHED GET https://api.github.com/repos/twbs/bootstrap/git/trees/2c2b5c714834814d7efd7ee910f7974bd7bd1143...
  CACHED GET https://api.github.com/repos/twbs/bootstrap/git/trees/2c2b5c714834814d7efd7ee910f7974bd7bd1143...
rake aborted!
undefined method `[]' for nil:NilClass
/home/bass/Dropbox/testomgeving/bootstrap-sass-master/tasks/converter/network.rb:71:in `get_tree_sha'
/home/bass/Dropbox/testomgeving/bootstrap-sass-master/tasks/converter/less_conversion.rb:144:in `bootstrap_less_files'
/home/bass/Dropbox/testomgeving/bootstrap-sass-master/tasks/converter/less_conversion.rb:54:in `process_stylesheet_assets'
/home/bass/Dropbox/testomgeving/bootstrap-sass-master/tasks/converter.rb:63:in `process_bootstrap'
/home/bass/Dropbox/testomgeving/bootstrap-sass-master/Rakefile:26:in `block in <top (required)>'
Tasks: TOP => convert
(See full trace by running task with --trace)
```

It seems the same question is ask here: http://stackoverflow.com/questions/24682532/how-to-use-bootstrap-sass-rake-convert-to-create-sass-version-of-bootstrap-v3-0

**Comment by deshipu** [comment]
Sorry for commenting on an old issue, but I'm getting the same error, but this time it's without the commit hash:

```
> rake convert
git ls-remote https://github.com/twbs/bootstrap master
Convert Bootstrap LESS to Sass
 repo   : https://github.com/twbs/bootstrap
 branch : 481540800d3c242c8152bbfed7fd60dbf59437c6 https://github.com/twbs/bootstrap/tree/master
 save to: {"js":"assets/javascripts/bootstrap","scss":"assets/stylesheets/bootstrap","fonts":"assets/fonts/bootstrap"}
 twbs cache: tmp/converter-cache-bootstrap
------------------------------------------------------------
Processing fonts...
  GET https://api.github.com/repos/twbs/bootstrap/git/trees/481540800d3c242c8152bbfed7fd60dbf59437c6?recursive=1...
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/.../bootstrap-sass/tasks/converter/network.rb:82:in `get_tree_sha'
/.../bootstrap-sass/tasks/converter/network.rb:11:in `get_file_paths'
/.../bootstrap-sass/tasks/converter/network.rb:7:in `get_paths_by_type'
/.../bootstrap-sass/tasks/converter/fonts_conversion.rb:13:in `bootstrap_font_files'
/.../bootstrap-sass/tasks/converter/fonts_conversion.rb:5:in `process_font_assets'
/.../bootstrap-sass/tasks/converter.rb:62:in `process_bootstrap'
/.../bootstrap-sass/Rakefile:59:in `block in <top (required)>'
/usr/share/gems/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => convert
(See full trace by running task with --trace)
```
