### ISSUE TITLE
@extend .btn; makes "undefined method `type' for .focus:Sass::Selector::Class"

### ISSUE THREAD

**Issue by woohoou** [twbs/bootstrap-sass#769]
When I extend .btn with a :not(.default) notation I have the message undefined method `type' for .focus:Sass::Selector::Class
```
a:not(.default) {
  @extend .btn;
}
```
Happened with version bootstrap-sass 3.3.0.1, sass-rails 4.0.4 and compass-rails 2.0.0 (maybe compass or sass-rails aren't involved.

**Comment by cvrebert** [comment]
@woohoou What exact version of Sass itself are you using?

**Comment by woohoou** [comment]
@cvrebert Hi Chris, should be 3.2.2

**Comment by glebm** [comment]
@woohuu Please upgrade to 3.2.19+.

**Comment by jokklan** [comment]
I get the same error with sass version 3.4.12

**Comment by cvrebert** [comment]
@jokklan Please specify all relevant software versions that you're using.

**Comment by jokklan** [comment]
@cvrebert:
```
    sass (3.4.12)
    sass-rails (5.0.1)
    bootstrap-sass (3.3.3)
```

This is the backlog i get in sass:

```
NoMethodError - undefined method `type' for .focus:Sass::Selector::Class
  (in /Users/johanfrolich/Rails/white_album/backend/app/assets/stylesheets/backend/themes/white.scss):
  sass (3.4.12) lib/sass/selector/simple.rb:77:in `block in unify'
  sass (3.4.12) lib/sass/selector/simple.rb:77:in `unify'
  sass (3.4.12) lib/sass/selector/pseudo.rb:137:in `unify'
  sass (3.4.12) lib/sass/selector/simple_sequence.rb:240:in `block in unify'
  sass (3.4.12) lib/sass/selector/simple_sequence.rb:238:in `unify'
  sass (3.4.12) lib/sass/selector/simple_sequence.rb:195:in `block in do_extend'
  sass (3.4.12) lib/sass/selector/simple_sequence.rb:188:in `do_extend'
  sass (3.4.12) lib/sass/selector/sequence.rb:112:in `block in do_extend'
  sass (3.4.12) lib/sass/selector/sequence.rb:110:in `do_extend'
  sass (3.4.12) lib/sass/selector/comma_sequence.rb:71:in `block in do_extend'
  sass (3.4.12) lib/sass/selector/comma_sequence.rb:70:in `do_extend'
  sass (3.4.12) lib/sass/tree/visitors/extend.rb:44:in `visit_rule'
  sass (3.4.12) lib/sass/tree/visitors/base.rb:36:in `visit'
  sass (3.4.12) lib/sass/tree/visitors/extend.rb:28:in `visit'
  sass (3.4.12) lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
  sass (3.4.12) lib/sass/tree/visitors/base.rb:52:in `visit_children'
  sass (3.4.12) lib/sass/tree/visitors/extend.rb:37:in `visit_children'
  sass (3.4.12) lib/sass/tree/visitors/base.rb:38:in `visit'
  sass (3.4.12) lib/sass/tree/visitors/extend.rb:28:in `visit'
  sass (3.4.12) lib/sass/tree/visitors/extend.rb:15:in `visit'
  sass (3.4.12) lib/sass/tree/root_node.rb:39:in `css_tree'
  sass (3.4.12) lib/sass/tree/root_node.rb:20:in `render'
  sass (3.4.12) lib/sass/engine.rb:268:in `render'
  compass-rails (2.0.4) lib/compass-rails/patches/sass_importer.rb:48:in `evaluate'
  tilt (1.4.1) lib/tilt/template.rb:103:in `render'
  sprockets (2.12.3) lib/sprockets/context.rb:197:in `block in evaluate'
  sprockets (2.12.3) lib/sprockets/context.rb:194:in `evaluate'
  sprockets (2.12.3) lib/sprockets/processed_asset.rb:12:in `initialize'
  sprockets (2.12.3) lib/sprockets/base.rb:374:in `block in build_asset'
  sprockets (2.12.3) lib/sprockets/base.rb:395:in `circular_call_protection'
  sprockets (2.12.3) lib/sprockets/base.rb:373:in `build_asset'
  sprockets (2.12.3) lib/sprockets/index.rb:94:in `block in build_asset'
  sprockets (2.12.3) lib/sprockets/caching.rb:58:in `cache_asset'
  sprockets (2.12.3) lib/sprockets/index.rb:93:in `build_asset'
  sprockets (2.12.3) lib/sprockets/base.rb:287:in `find_asset'
  sprockets (2.12.3) lib/sprockets/index.rb:61:in `find_asset'
  sprockets (2.12.3) lib/sprockets/bundled_asset.rb:16:in `initialize'
  sprockets (2.12.3) lib/sprockets/base.rb:377:in `build_asset'
  sprockets (2.12.3) lib/sprockets/index.rb:94:in `block in build_asset'
  sprockets (2.12.3) lib/sprockets/caching.rb:58:in `cache_asset'
  sprockets (2.12.3) lib/sprockets/index.rb:93:in `build_asset'
  sprockets (2.12.3) lib/sprockets/base.rb:287:in `find_asset'
  sprockets (2.12.3) lib/sprockets/index.rb:61:in `find_asset'
  sprockets (2.12.3) lib/sprockets/environment.rb:75:in `find_asset'
  sprockets (2.12.3) lib/sprockets/base.rb:295:in `[]'
  sprockets-rails (2.2.4) lib/sprockets/rails/helper.rb:230:in `lookup_asset_for_path'
  sprockets-rails (2.2.4) lib/sprockets/rails/helper.rb:190:in `check_errors_for'
  sprockets-rails (2.2.4) lib/sprockets/rails/helper.rb:159:in `block in stylesheet_link_tag'
  sprockets-rails (2.2.4) lib/sprockets/rails/helper.rb:158:in `stylesheet_link_tag'
```

**Comment by cvrebert** [comment]
`themes/white.scss` isn't part of Bootstrap. Could you post that file?

**Comment by jokklan** [comment]
It's pretty big, but this is the part that fails:
```scss
.check-with-btn-base {
  &:before {
    @extend .btn;
    @extend .btn-default;

    margin-top:-4px;
    margin-left:-2px;
  }
}
```

**Comment by cvrebert** [comment]
I can repro and was able to craft a reduced testcase!
Filed a Sass bug: https://github.com/sass/sass/issues/1656

**Comment by jokklan** [comment]
@cvrebert thank you! Sorry I didn't do that myself... :)
